// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.alibaba.middleware.race.mom.protobuf;

public final class ProtoMessage {
  private ProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string msgId = 1;
    /**
     * <code>required string msgId = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    java.lang.String getMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    // optional string topic = 2;
    /**
     * <code>optional string topic = 2;</code>
     */
    boolean hasTopic();
    /**
     * <code>optional string topic = 2;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>optional string topic = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    // optional string body = 3;
    /**
     * <code>optional string body = 3;</code>
     */
    boolean hasBody();
    /**
     * <code>optional string body = 3;</code>
     */
    java.lang.String getBody();
    /**
     * <code>optional string body = 3;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    // optional string groupId = 4;
    /**
     * <code>optional string groupId = 4;</code>
     */
    boolean hasGroupId();
    /**
     * <code>optional string groupId = 4;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>optional string groupId = 4;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    // optional string filter = 5;
    /**
     * <code>optional string filter = 5;</code>
     */
    boolean hasFilter();
    /**
     * <code>optional string filter = 5;</code>
     */
    java.lang.String getFilter();
    /**
     * <code>optional string filter = 5;</code>
     */
    com.google.protobuf.ByteString
        getFilterBytes();

    // optional fixed64 bornTime = 6;
    /**
     * <code>optional fixed64 bornTime = 6;</code>
     */
    boolean hasBornTime();
    /**
     * <code>optional fixed64 bornTime = 6;</code>
     */
    long getBornTime();

    // optional uint32 messageType = 7;
    /**
     * <code>optional uint32 messageType = 7;</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional uint32 messageType = 7;</code>
     */
    int getMessageType();

    // repeated string propertiesKey = 8;
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    java.util.List<java.lang.String>
    getPropertiesKeyList();
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    int getPropertiesKeyCount();
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    java.lang.String getPropertiesKey(int index);
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    com.google.protobuf.ByteString
        getPropertiesKeyBytes(int index);

    // repeated string propertiesValue = 9;
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    java.util.List<java.lang.String>
    getPropertiesValueList();
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    int getPropertiesValueCount();
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    java.lang.String getPropertiesValue(int index);
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    com.google.protobuf.ByteString
        getPropertiesValueBytes(int index);
  }
  /**
   * Protobuf type {@code netty.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msgId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              topic_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              body_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              groupId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              filter_ = input.readBytes();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              bornTime_ = input.readFixed64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              messageType_ = input.readUInt32();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                propertiesKey_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              propertiesKey_.add(input.readBytes());
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                propertiesValue_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000100;
              }
              propertiesValue_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          propertiesKey_ = new com.google.protobuf.UnmodifiableLazyStringList(propertiesKey_);
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          propertiesValue_ = new com.google.protobuf.UnmodifiableLazyStringList(propertiesValue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.middleware.race.mom.protobuf.ProtoMessage.internal_static_netty_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.middleware.race.mom.protobuf.ProtoMessage.internal_static_netty_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message.class, com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private java.lang.Object msgId_;
    /**
     * <code>required string msgId = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string topic = 2;
    public static final int TOPIC_FIELD_NUMBER = 2;
    private java.lang.Object topic_;
    /**
     * <code>optional string topic = 2;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string topic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string body = 3;
    public static final int BODY_FIELD_NUMBER = 3;
    private java.lang.Object body_;
    /**
     * <code>optional string body = 3;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string body = 3;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string body = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string groupId = 4;
    public static final int GROUPID_FIELD_NUMBER = 4;
    private java.lang.Object groupId_;
    /**
     * <code>optional string groupId = 4;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string groupId = 4;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string groupId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string filter = 5;
    public static final int FILTER_FIELD_NUMBER = 5;
    private java.lang.Object filter_;
    /**
     * <code>optional string filter = 5;</code>
     */
    public boolean hasFilter() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string filter = 5;</code>
     */
    public java.lang.String getFilter() {
      java.lang.Object ref = filter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filter = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFilterBytes() {
      java.lang.Object ref = filter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional fixed64 bornTime = 6;
    public static final int BORNTIME_FIELD_NUMBER = 6;
    private long bornTime_;
    /**
     * <code>optional fixed64 bornTime = 6;</code>
     */
    public boolean hasBornTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional fixed64 bornTime = 6;</code>
     */
    public long getBornTime() {
      return bornTime_;
    }

    // optional uint32 messageType = 7;
    public static final int MESSAGETYPE_FIELD_NUMBER = 7;
    private int messageType_;
    /**
     * <code>optional uint32 messageType = 7;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 messageType = 7;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    // repeated string propertiesKey = 8;
    public static final int PROPERTIESKEY_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList propertiesKey_;
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    public java.util.List<java.lang.String>
        getPropertiesKeyList() {
      return propertiesKey_;
    }
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    public int getPropertiesKeyCount() {
      return propertiesKey_.size();
    }
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    public java.lang.String getPropertiesKey(int index) {
      return propertiesKey_.get(index);
    }
    /**
     * <code>repeated string propertiesKey = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPropertiesKeyBytes(int index) {
      return propertiesKey_.getByteString(index);
    }

    // repeated string propertiesValue = 9;
    public static final int PROPERTIESVALUE_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList propertiesValue_;
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    public java.util.List<java.lang.String>
        getPropertiesValueList() {
      return propertiesValue_;
    }
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    public int getPropertiesValueCount() {
      return propertiesValue_.size();
    }
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    public java.lang.String getPropertiesValue(int index) {
      return propertiesValue_.get(index);
    }
    /**
     * <code>repeated string propertiesValue = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPropertiesValueBytes(int index) {
      return propertiesValue_.getByteString(index);
    }

    private void initFields() {
      msgId_ = "";
      topic_ = "";
      body_ = "";
      groupId_ = "";
      filter_ = "";
      bornTime_ = 0L;
      messageType_ = 0;
      propertiesKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      propertiesValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBodyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getGroupIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFilterBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFixed64(6, bornTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, messageType_);
      }
      for (int i = 0; i < propertiesKey_.size(); i++) {
        output.writeBytes(8, propertiesKey_.getByteString(i));
      }
      for (int i = 0; i < propertiesValue_.size(); i++) {
        output.writeBytes(9, propertiesValue_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBodyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGroupIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFilterBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(6, bornTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, messageType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < propertiesKey_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(propertiesKey_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPropertiesKeyList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < propertiesValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(propertiesValue_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPropertiesValueList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alibaba.middleware.race.mom.protobuf.ProtoMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.middleware.race.mom.protobuf.ProtoMessage.internal_static_netty_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.middleware.race.mom.protobuf.ProtoMessage.internal_static_netty_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message.class, com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message.Builder.class);
      }

      // Construct using com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        groupId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        filter_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        bornTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        propertiesKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        propertiesValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.middleware.race.mom.protobuf.ProtoMessage.internal_static_netty_Message_descriptor;
      }

      public com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message getDefaultInstanceForType() {
        return com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message.getDefaultInstance();
      }

      public com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message build() {
        com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message buildPartial() {
        com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message result = new com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.filter_ = filter_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bornTime_ = bornTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.messageType_ = messageType_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          propertiesKey_ = new com.google.protobuf.UnmodifiableLazyStringList(
              propertiesKey_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.propertiesKey_ = propertiesKey_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          propertiesValue_ = new com.google.protobuf.UnmodifiableLazyStringList(
              propertiesValue_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.propertiesValue_ = propertiesValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message) {
          return mergeFrom((com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message other) {
        if (other == com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasTopic()) {
          bitField0_ |= 0x00000002;
          topic_ = other.topic_;
          onChanged();
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000004;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasGroupId()) {
          bitField0_ |= 0x00000008;
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.hasFilter()) {
          bitField0_ |= 0x00000010;
          filter_ = other.filter_;
          onChanged();
        }
        if (other.hasBornTime()) {
          setBornTime(other.getBornTime());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (!other.propertiesKey_.isEmpty()) {
          if (propertiesKey_.isEmpty()) {
            propertiesKey_ = other.propertiesKey_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensurePropertiesKeyIsMutable();
            propertiesKey_.addAll(other.propertiesKey_);
          }
          onChanged();
        }
        if (!other.propertiesValue_.isEmpty()) {
          if (propertiesValue_.isEmpty()) {
            propertiesValue_ = other.propertiesValue_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensurePropertiesValueIsMutable();
            propertiesValue_.addAll(other.propertiesValue_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.middleware.race.mom.protobuf.ProtoMessage.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string msgId = 1;
      private java.lang.Object msgId_ = "";
      /**
       * <code>required string msgId = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      // optional string topic = 2;
      private java.lang.Object topic_ = "";
      /**
       * <code>optional string topic = 2;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000002);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string topic = 2;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }

      // optional string body = 3;
      private java.lang.Object body_ = "";
      /**
       * <code>optional string body = 3;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string body = 3;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string body = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string body = 3;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 3;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000004);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 3;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        body_ = value;
        onChanged();
        return this;
      }

      // optional string groupId = 4;
      private java.lang.Object groupId_ = "";
      /**
       * <code>optional string groupId = 4;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string groupId = 4;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string groupId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string groupId = 4;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 4;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupId = 4;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        groupId_ = value;
        onChanged();
        return this;
      }

      // optional string filter = 5;
      private java.lang.Object filter_ = "";
      /**
       * <code>optional string filter = 5;</code>
       */
      public boolean hasFilter() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string filter = 5;</code>
       */
      public java.lang.String getFilter() {
        java.lang.Object ref = filter_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          filter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filter = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFilterBytes() {
        java.lang.Object ref = filter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filter = 5;</code>
       */
      public Builder setFilter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        filter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filter = 5;</code>
       */
      public Builder clearFilter() {
        bitField0_ = (bitField0_ & ~0x00000010);
        filter_ = getDefaultInstance().getFilter();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filter = 5;</code>
       */
      public Builder setFilterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        filter_ = value;
        onChanged();
        return this;
      }

      // optional fixed64 bornTime = 6;
      private long bornTime_ ;
      /**
       * <code>optional fixed64 bornTime = 6;</code>
       */
      public boolean hasBornTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional fixed64 bornTime = 6;</code>
       */
      public long getBornTime() {
        return bornTime_;
      }
      /**
       * <code>optional fixed64 bornTime = 6;</code>
       */
      public Builder setBornTime(long value) {
        bitField0_ |= 0x00000020;
        bornTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 bornTime = 6;</code>
       */
      public Builder clearBornTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bornTime_ = 0L;
        onChanged();
        return this;
      }

      // optional uint32 messageType = 7;
      private int messageType_ ;
      /**
       * <code>optional uint32 messageType = 7;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 messageType = 7;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional uint32 messageType = 7;</code>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000040;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 messageType = 7;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        messageType_ = 0;
        onChanged();
        return this;
      }

      // repeated string propertiesKey = 8;
      private com.google.protobuf.LazyStringList propertiesKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePropertiesKeyIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          propertiesKey_ = new com.google.protobuf.LazyStringArrayList(propertiesKey_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public java.util.List<java.lang.String>
          getPropertiesKeyList() {
        return java.util.Collections.unmodifiableList(propertiesKey_);
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public int getPropertiesKeyCount() {
        return propertiesKey_.size();
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public java.lang.String getPropertiesKey(int index) {
        return propertiesKey_.get(index);
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPropertiesKeyBytes(int index) {
        return propertiesKey_.getByteString(index);
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public Builder setPropertiesKey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesKeyIsMutable();
        propertiesKey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public Builder addPropertiesKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesKeyIsMutable();
        propertiesKey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public Builder addAllPropertiesKey(
          java.lang.Iterable<java.lang.String> values) {
        ensurePropertiesKeyIsMutable();
        super.addAll(values, propertiesKey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public Builder clearPropertiesKey() {
        propertiesKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesKey = 8;</code>
       */
      public Builder addPropertiesKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesKeyIsMutable();
        propertiesKey_.add(value);
        onChanged();
        return this;
      }

      // repeated string propertiesValue = 9;
      private com.google.protobuf.LazyStringList propertiesValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePropertiesValueIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          propertiesValue_ = new com.google.protobuf.LazyStringArrayList(propertiesValue_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public java.util.List<java.lang.String>
          getPropertiesValueList() {
        return java.util.Collections.unmodifiableList(propertiesValue_);
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public int getPropertiesValueCount() {
        return propertiesValue_.size();
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public java.lang.String getPropertiesValue(int index) {
        return propertiesValue_.get(index);
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public com.google.protobuf.ByteString
          getPropertiesValueBytes(int index) {
        return propertiesValue_.getByteString(index);
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public Builder setPropertiesValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesValueIsMutable();
        propertiesValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public Builder addPropertiesValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesValueIsMutable();
        propertiesValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public Builder addAllPropertiesValue(
          java.lang.Iterable<java.lang.String> values) {
        ensurePropertiesValueIsMutable();
        super.addAll(values, propertiesValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public Builder clearPropertiesValue() {
        propertiesValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string propertiesValue = 9;</code>
       */
      public Builder addPropertiesValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertiesValueIsMutable();
        propertiesValue_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoMessage.proto\022\005netty\"\255\001\n\007Message\022" +
      "\r\n\005msgId\030\001 \002(\t\022\r\n\005topic\030\002 \001(\t\022\014\n\004body\030\003 " +
      "\001(\t\022\017\n\007groupId\030\004 \001(\t\022\016\n\006filter\030\005 \001(\t\022\020\n\010" +
      "bornTime\030\006 \001(\006\022\023\n\013messageType\030\007 \001(\r\022\025\n\rp" +
      "ropertiesKey\030\010 \003(\t\022\027\n\017propertiesValue\030\t " +
      "\003(\tB*\n(com.alibaba.middleware.race.mom.p" +
      "rotobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_netty_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_netty_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netty_Message_descriptor,
              new java.lang.String[] { "MsgId", "Topic", "Body", "GroupId", "Filter", "BornTime", "MessageType", "PropertiesKey", "PropertiesValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
